stages:
  - test

run-tests:
  stage: test
  script:
    - /Applications/apache-maven-3.8.6/bin/mvn clean test
    - /usr/local/bin/allure generate target/allure-results --clean -o target/allure-report
  artifacts:
    when: always
    paths:
      - target/allure-report/
      - target/allure-results/
